dist: bionic
language: python
python:
  - "3.7"

cache:
  pip: true

install:
  - pip install -r requirements.txt
# command to run tests
script:
  # - pylint -j $(nproc) --rcfile=.pylintrc python scripts
  - python scripts/lint_checker.py
